baseURL = "/"
languageCode = "en-gb"
theme = "hello-friend"

[params]
defaultTheme = "dark"
showMenuItems = 2
showReadingTime = true

[languages]
    [languages.en]
    title = "acode.ninja"
    subtitle = "Adventures of a code ninja"
    keywords = "software developer, coder, learning to code"
    copyright = "Lawrence Goldstien"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
        [languages.en.params.logo]
        logoText = "acode.ninja"
        logoHomeLink = "/"
